# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        upload_picture:
            uri_prefix: /images/uploads
            upload_destination: "%kernel.project_dir%/public/images/uploads"

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
