controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: "/"
        trk: "/trk"
    requirements:
        _locale: fr|trk

kernel:
    resource: ../../src/Kernel.php
    type: annotation
